### PR TITLE
Fixed markup/image issues in Python tutorial, adds .gitignore

### PR DESCRIPTION
**Pull request by simonprickett**

### CODE REVIEW

**Review by slorello89 — CHANGES_REQUESTED** [review]
@simonprickett , move the images up 2 levels. To be even with `stack-python.md`

**Review by slorello89 — CHANGES_REQUESTED** [review]
See comment

**Comment by simonprickett** [comment]
@slorello89 fixed, thanks.

**Review by zalenskiSofteq — COMMENTED** [review]
In the RedisInsight today (2.0.5) was a release and was added a Tree view in the Browser
I think we can add image with a Tree view)

**Comment by simonprickett** [comment]
> In the RedisInsight today (2.0.5) was a release and was added a Tree view in the Browser I think we can add image with a Tree view)

Not a big deal and shouldn't prevent merging this to fix the markup issue and fact that images are missing in live.  The video workshop for this was recorded with 2.0.4.

**Comment by zalenskiSofteq** [comment]
> Not a big deal and shouldn't prevent merging this to fix the markup issue and fact that images are missing in live. The video workshop for this was recorded with 2.0.4.

Agree
Not a big deal

**Pull request merged**
